### ISSUE TITLE
not able to build archive folder 

### ISSUE THREAD

**Issue by sssuourabh** [kodmunki/ku4objc_temp#1]
not able to get archieve folder for universal binary

**Comment by kodmunki** [comment]
Very sorry to inform you that this is certainly an issue on you end. There is nothing that we can do on this side, as this project and, more importantly, the process that it stands as an example for: https://kodmunki.wordpress.com/2015/03/04/cocoa-touch-frameworks-for-ios8-remix/ continue to work as expected for us and many, many others! -- Might I suggest, if you are interested in using this process, that you follow the link in this post and be vigilant in following the instructions. If you do, you will succeed! Thank you for checking in. :{)}
